In [ ]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import  np_utils

In [ ]:
base = pd.read_csv('iris.csv')

Esse arquivo .csv não esta dividido entre previores e classe. O processo a seguir faz essa divisão.
O arquivo possui 5 colunas, na quinta colona que estão as classes.

In [ ]:
previsores = base.iloc[:, 0:4].values
classe = base.iloc[:, 4].values

In [ ]:
#Transforma de atributo categorico para atribut numerico
from sklearn.preprocessing import LabelEncoder

Ao inves da categoria de saida ser o nome ela passa a ser um valor. Conforme apresentado abaixo:

iris setosa     1 0 0

iris virginica  0 1 0

iris versicolor 0 0 1 

In [ ]:
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)

In [ ]:
from sklearn.model_selection import train_test_split

O processo a seguir realiza a divisão para treinamentos e testes.

In [ ]:
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size = 0.25)

In [ ]:
classificador = Sequential()
classificador.add(Dense(units= 4, activation= 'relu', input_dim = 4))
classificador.add(Dense(units= 4, activation= 'relu'))
classificador.add(Dense(units= 3, activation= 'softmax'))
classificador.compile(optimizer= 'adam', loss = 'categorical_crossentropy',
                      metrics = ['categorical_accuracy'])

In [ ]:
classificador.fit(previsores_treinamento, classe_treinamento, batch_size= 10, epochs= 1000)

Epoch 1/1000
12/12 [==============================] - 1s 2ms/step - loss: 1.9817 - categorical_accuracy: 0.3482
Epoch 2/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.7169 - categorical_accuracy: 0.3482
Epoch 3/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.4663 - categorical_accuracy: 0.3482
Epoch 4/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.2025 - categorical_accuracy: 0.3482
Epoch 5/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.0023 - categorical_accuracy: 0.3482
Epoch 6/1000
12/12 [==============================] - 0s 4ms/step - loss: 0.8959 - categorical_accuracy: 0.3482
Epoch 7/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.8513 - categorical_accuracy: 0.3482
Epoch 8/1000
12/12 [==============================] - 0s 3ms/step - loss: 0.8461 - categorical_accuracy: 0.4464
Epoch 9/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.8368 - categorical_accuracy:

In [ ]:
resultado = classificador.evaluate(previsores_teste, classe_teste)

2/2 [==============================] - 0s 8ms/step - loss: 0.0640 - categorical_accuracy: 0.9737


In [ ]:
previsoes = classificador.predict(previsores_teste)
previsoes = (previsoes > 0.5)
print(previsoes)

[[ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]]


In [ ]:
import numpy as np

In [ ]:
#Converter para retornar o indice de maior valor
classe_teste2 = [np.argmax(t) for t in classe_teste]
#print(classe_teste2)
previsoes2 = [np.argmax(t) for t in previsoes]
#print(previsoes2)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
matriz = confusion_matrix(previsoes2, classe_teste2)
print(matriz)

[[16  0  0]
 [ 0 11  1]
 [ 0  0 10]]
